# Generated by Django 5.0.4 on 2024-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English')], max_length=20)),
                ('category', models.CharField(choices=[('comedy', 'comedy'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('action', 'Action'), ('adventure', 'Adventure')], max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='video')),
                ('time', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=150)),
            ],
        ),
    ]
